name: 'Build and install ArcDependencies'
description: 'A GH Actions to easily install ArcDependencies from Arcane Framework'

inputs:
  source_dir:
    description: '[IN] Directory with arcdependencies sources'
    type: string
    required: true
  build_dir:
    description: '[OUT] Directory for build files'
    type: string
    required: true
  install_dir:
    description: '[OUT] Directory for install files'
    type: string
    required: true
  arccon_install_dir:
    description: '[IN] Directory with arccon installation'
    type: string
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure arcdependencies
      shell: bash
      run: |
        cmake \
        -S ${{ inputs.source_dir }} \
        -B ${{ inputs.build_dir }} \
        -GNinja \
        -DCMAKE_INSTALL_PREFIX=${{ inputs.install_dir }} \
        -DArccon_DIR=${{ inputs.arccon_install_dir }}/share/cmake/Arccon

    - name: Install arcdependencies
      shell: bash
      run: |
        cmake --install ${{ inputs.build_dir }}
