name: 'Build and install Arcane'
description: 'A GH Actions to easily install Arcane from Arcane Framework'

inputs:
  source_dir:
    description: '[IN] Directory with arcane sources'
    type: string
    required: true
  build_dir:
    description: '[OUT] Directory for build files'
    type: string
    required: true
  install_dir:
    description: '[OUT] Directory for install files'
    type: string
    required: true
  log_dir:
    description: '[OUT] Log directory to save logs'
    type: string
    required: false
    default: ""
  arccon_install_dir:
    description: '[IN] Directory with arccon installation'
    type: string
    required: true
  arcdependencies_install_dir:
    description: '[IN] Directory with arcdependencies installation'
    type: string
    required: true
  axlstar_install_dir:
    description: '[IN] Directory with axlstar installation'
    type: string
    required: true
  arccore_install_dir:
    description: '[IN] Directory with arccore installation'
    type: string
    required: true
  cache_dir:
    description: '[IN/OUT] Cache directory to accelerate compile time'
    type: string
    required: false
  cmake_additionnal_args:
    description: 'Additionnal arguments for configure'
    type: string
    required: false
    default: ""
  type_build:
    description: 'Type of build (Debug, Check, Release)'
    type: string
    required: false
    default: "Release"
  use_ninja:
    description: 'Use ninja instead of make'
    type: boolean
    required: false
    default: true
  use_shared_libs:
    description: 'Use shared libs instead of static libs'
    type: boolean
    required: false
    default: true
  verbose:
    description: 'Add verbose args for make/ninja'
    type: boolean
    required: false
    default: false
  compilo:
    description: 'Compiler (GCC, CLang)'
    type: string
    required: false
    default: "GCC"
  with_cuda:
    description: 'Compile with CUDA too ?'
    type: boolean
    required: false
    default: false
  with_samples:
    description: 'Compile samples too ?'
    type: boolean
    required: false
    default: false


runs:
  using: "composite"
  steps:
    - name: Set ccache var env
      if: "${{ inputs.cache_dir != '' }}"
      shell: bash
      run: |
        echo "CCACHE_COMPRESS=true" >> $GITHUB_ENV
        echo "CCACHE_COMPRESSLEVEL=6" >> $GITHUB_ENV
        echo "CCACHE_DIR=${{ inputs.cache_dir }}" >> $GITHUB_ENV
        echo "CCACHE_MAXSIZE=5G" >> $GITHUB_ENV
        echo "ACTION_CMAKE_ADD_ARGS=-DCMAKE_CXX_COMPILER_LAUNCHER=ccache" >> $GITHUB_ENV

    - name: Compute build type
      shell: bash
      run: |
        if [[ "${{ inputs.type_build }}" == "Check" ]]; then
          CMAKE_BUILD_TYPE="Release"
        else
          CMAKE_BUILD_TYPE="${{ inputs.type_build }}"
        fi
        echo "ACTION_CMAKE_ADD_ARGS=${{ env.ACTION_CMAKE_ADD_ARGS }} \
        -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE \
        -DARCCORE_BUILD_MODE=${{ inputs.type_build }} \
        " >> $GITHUB_ENV

    - name: Personalize compiler
      shell: bash
      run: |
        if [[ "${{ inputs.compilo }}" == "CLang" ]]; then
          echo "ACTION_CMAKE_ADD_ARGS=${{ env.ACTION_CMAKE_ADD_ARGS }} -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++" >> $GITHUB_ENV
        else
          echo "ACTION_CMAKE_ADD_ARGS=${{ env.ACTION_CMAKE_ADD_ARGS }} -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++" >> $GITHUB_ENV
        fi

    # Oui, ici, le type 'boolean' ne semble pas l'interesser plus que ça...
    - name: Add cuda
      if: "${{ inputs.with_cuda == 'true' }}"
      shell: bash
      run: |
        echo "ACTION_CMAKE_ADD_ARGS=${{ env.ACTION_CMAKE_ADD_ARGS }} -DARCANE_ACCELERATOR_MODE=CUDANVCC -DCMAKE_CUDA_COMPILER=nvcc" >> $GITHUB_ENV

    - name: Use ninja
      if: "${{ inputs.use_ninja == 'true' }}"
      shell: bash
      run: |
        echo "ACTION_CMAKE_ADD_ARGS=${{ env.ACTION_CMAKE_ADD_ARGS }} -GNinja" >> $GITHUB_ENV

    - name: Use shared libs
      if: "${{ inputs.use_shared_libs == 'true' }}"
      shell: bash
      run: |
        echo "ACTION_CMAKE_ADD_ARGS=${{ env.ACTION_CMAKE_ADD_ARGS }} -DBUILD_SHARED_LIBS=ON" >> $GITHUB_ENV

    - name: Verbose building
      if: "${{ inputs.verbose == 'true' }}"
      shell: bash
      run: |
        echo "ACTION_CMAKE_ADD_ARGS=${{ env.ACTION_CMAKE_ADD_ARGS }} -DCMAKE_VERBOSE_MAKEFILE=TRUE" >> $GITHUB_ENV

    - name: Configure arcane
      shell: bash
      run: |
        cmake \
        -S ${{ inputs.source_dir }} \
        -B ${{ inputs.build_dir }} \
        -GNinja \
        -DBUILD_SHARED_LIBS=ON \
        -DCMAKE_INSTALL_PREFIX=${{ inputs.install_dir }} \
        -DArccon_DIR=${{ inputs.arccon_install_dir }}/share/cmake/Arccon \
        -DArcDependencies_DIR=${{ inputs.arcdependencies_install_dir }}/share/cmake/ArcDependencies \
        -DAxlstar_DIR=${{ inputs.axlstar_install_dir }}/share/cmake/Axlstar \
        -DArccore_DIR=${{ inputs.arccore_install_dir }}/lib/cmake/Arccore \
        ${{ inputs.cmake_additionnal_args }} \
        ${{ env.ACTION_CMAKE_ADD_ARGS }}

    - name: Build arcane
      shell: bash
      run: |
        cmake --build ${{ inputs.build_dir }}

    - name: Install arcane
      shell: bash
      run: |
        cmake --install ${{ inputs.build_dir }}

    - name: Configure samples
      if: "${{ inputs.with_samples == 'true' }}"
      shell: bash
      run: |
        cmake \
        -S ${{ inputs.build_dir }}/samples \
        -B ${{ inputs.build_dir }}/builddir_samples \
        ${{ inputs.cmake_additionnal_args }} \
        ${{ env.ACTION_CMAKE_ADD_ARGS }}

    - name: Build samples
      if: "${{ inputs.with_samples == 'true' }}"
      shell: bash
      run: |
        cmake --build ${{ inputs.build_dir }}/builddir_samples

    - name: Get ccache status
      if: "${{ inputs.cache_dir != '' }}"
      shell: bash
      run: ccache -s

    - name: Save logs
      if: ${{ always() && inputs.log_dir != '' }}
      shell: bash
      run: |
        mkdir -p "${{ inputs.log_dir }}"
        cp -r "${{ inputs.build_dir }}/CMakeFiles" "${{ inputs.log_dir }}" || true
        cp "${{ inputs.build_dir }}/build.ninja" "${{ inputs.log_dir }}" || true
        cp "${{ inputs.build_dir }}/CMakeCache.txt" "${{ inputs.log_dir }}" || true
        mkdir -p "${{ inputs.log_dir }}/samples"
        cp -r "${{ inputs.build_dir }}/builddir_samples/CMakeFiles" "${{ inputs.log_dir }}/samples" || true
