name: 'Check if the requested runner is available'

on:
  workflow_call:
    inputs:
      requested_runner_tag:
        description: 'Requested runner tag'
        type: string
        required: false
        default: 'ubuntu-latest'
      is_requested_runner_a_gpu_runner:
        description: 'Requested runner is a GPU runner ? (true/false)'
        type: string
        required: false
        default: 'false'
    outputs:
      runner_tag:
        description: "Available runner tag"
        value: ${{ jobs.check-runner.outputs.runner_tag }}
      is_a_gpu_runner:
        description: "Available runner is a GPU runner ? (true/false)"
        value: ${{ jobs.check-runner.outputs.is_a_gpu_runner }}

jobs:
  check-runner:
    # Based on: https://github.com/orgs/community/discussions/20019#discussioncomment-13391111
    # We check whether the requested runner is available.
    # Otherwise, we use a GH runner.
    name: 'Check runner'
    runs-on: ubuntu-latest
    outputs:
      runner_tag: ${{ steps.final.outputs.runner_tag }}
      is_a_gpu_runner: ${{ steps.final.outputs.is_a_gpu_runner }}

    steps:
      # This step is executed if a self-hosted runner is requested.
      # This step may fail if the secrets are not accessible (fork,
      # for example), in this case we continue anyway (the runner
      # will be a GH runner, see "final" step).
      - name: Generate a token for reading available runners
        if: "${{ inputs.requested_runner_tag != 'ubuntu-latest' }}"
        continue-on-error: true
        id: generate-token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ secrets.RUNNERS_APP_ID }}
          private-key: ${{ secrets.RUNNERS_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      # This step is executed if a self-hosted runner is requested
      # and if the previous step was successful.
      # This step may fail if the app that provides us the
      # token is not installed in the organization.
      - name: Check available runners
        if: "${{ inputs.requested_runner_tag != 'ubuntu-latest' && steps.generate-token.outcome == 'success' }}"
        continue-on-error: true
        id: set-runner
        env:
           AUTH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          runners=$(curl -s -H "Accept: application/vnd.github+json" -H "Authorization: token $AUTH_TOKEN" "$GITHUB_API_URL/orgs/$GITHUB_REPOSITORY_OWNER/actions/runners")
          available=$(echo "$runners" | jq '.runners[] | select(.status == "online" and .labels[].name == "${{ inputs.requested_runner_tag }}")')
          if [ -n "$available" ]; then
            echo "RUNNER=${{ inputs.requested_runner_tag }}" >> $GITHUB_ENV
          else
            echo "RUNNER=ubuntu-latest" >> $GITHUB_ENV
            echo "::error::Self-hosted runner is not available, run on GH runner"
          fi

      # The self-hosted runner is chosen if it is accessible
      # and available.
      # Otherwise, a GH runner is used. 
      - name: Final choose
        id: final
        run: |
          if [[ "${{ inputs.requested_runner_tag }}" == "ubuntu-latest" ]]; then
            echo "runner_tag=ubuntu-latest" >> $GITHUB_OUTPUT
            echo "is_a_gpu_runner=false" >> $GITHUB_OUTPUT
            echo "::notice::The chosen runner is ubuntu-latest"
          elif [[ "${{ steps.set-runner.outcome }}" != "success" ]]; then
            echo "runner_tag=ubuntu-latest" >> $GITHUB_OUTPUT
            echo "is_a_gpu_runner=false" >> $GITHUB_OUTPUT
            echo "::warning::The selected runner is ubuntu-latest -- You requested ${{ inputs.requested_runner_tag }} but it is not available."
          else
            echo "runner_tag=${{ env.RUNNER }}" >> $GITHUB_OUTPUT
            echo "is_a_gpu_runner=${{ inputs.is_requested_runner_a_gpu_runner }}" >> $GITHUB_OUTPUT
            echo "::notice::The chosen runner is ${{ env.RUNNER }}"
          fi
