name: 'Build, install and test Arcane Framework'

on:
  workflow_call:
    inputs:
      image:
        description: 'Docker image for the workflow'
        type: string
        required: true

      compilo_name:
        description: 'Compiler name (gcc, clang)'
        type: string
        required: false
        default: 'gcc'
      compilo_version:
        description: 'Compiler version (12, 16, ...)'
        type: string
        required: false
        default: ''
      mpi:
        description: 'MPI (OMPI, MPICH)'
        type: string
        required: false
        default: 'OMPI'
      acc_compilo_name:
        description: 'Accelerator compiler name (cuda, acpp, clang_cuda, rocm)'
        type: string
        required: false
        default: ''
      acc_compilo_version:
        description: 'Accelerator compiler version (125, 126, ...) or empty str'
        type: string
        required: false
        default: ''
      use_mold:
        description: 'Use mold linker ? (true/false/auto)'
        type: string
        required: false
        default: 'auto'
      type_build:
        description: 'Type of build (Debug, Check, Release)'
        type: string
        required: false
        default: 'Release'
      cmake_additionnal_args:
        description: 'Additionnal arguments for configure'
        type: string
        required: false
        default: ''
      verbose:
        description: 'Add verbose args for make/ninja'
        type: boolean
        required: false
        default: false
      ccache_debug_mode:
        description: 'Activate CCache debug mode'
        type: boolean
        required: false
        default: false
      with_samples:
        description: 'Compile samples too ? Require install_dir.'
        type: boolean
        required: false
        default: true
      with_rand_script:
        description: 'Disabling randomly selected packages ?'
        type: boolean
        required: false
        default: false

      execute_tests:
        description: 'Execute tests ?'
        type: boolean
        required: false
        default: true
      cleanup_output_after_test:
        description: 'Remove output dir of each successful test ?'
        type: boolean
        required: false
        default: true
      excluded_tests:
        description: 'Regex with exclude tests'
        type: string
        required: false
        default: ''
      excluded_tests_with_labels:
        description: 'Labels of exclude tests'
        type: string
        required: false
        default: ''
      ctest_output_on_failure:
        description: 'Activate output on failure'
        type: boolean
        required: false
        default: true
      ctest_additionnal_args:
        description: 'Additionnal arguments for testing'
        type: string
        required: false
        default: ''

      use_cache:
        description: 'Use cache ? (true/false)'
        type: string
        required: false
        default: 'true'
      cache_key_prefix:
        description: 'Cache key prefix'
        type: string
        required: false
        default: 'aio'
      artifact_key_prefix:
        description: 'Artifact key prefix'
        type: string
        required: false
        default: 'artifact'

      runner_tag:
        description: 'Runner tag'
        type: string
        required: false
        default: 'ubuntu-latest'
        # options:
        # - 'ubuntu-latest'
        # - 'm-1'


env:
  # OpenMPI
  OMPI_ALLOW_RUN_AS_ROOT: 1
  OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
  # To tell OpenMPI we may use more processus than available cores
  OMPI_MCA_rmaps_base_oversubscribe : true
  ASAN_OPTIONS: 'detect_leaks=false'
  

jobs:
  check-runner:
    # Based on: https://github.com/orgs/community/discussions/20019#discussioncomment-13391111
    # We check whether the requested runner is available.
    # Otherwise, we use a GH runner.
    name: 'Check runner'
    runs-on: ubuntu-latest
    outputs:
      runner-tag: ${{ steps.final.outputs.runner-tag }}

    steps:
      # This step is executed if a self-hosted runner is requested.
      # This step may fail if the secrets are not accessible (fork,
      # for example), in this case we continue anyway (the runner
      # will be a GH runner, see "final" step).
      - name: Generate a token for reading available runners
        if: "${{ inputs.runner_tag != 'ubuntu-latest' }}"
        continue-on-error: true
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.RUNNERS_APP_ID }}
          private-key: ${{ secrets.RUNNERS_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      # This step is executed if a self-hosted runner is requested
      # and if the previous step was successful.
      # This step may fail if the app that provides us the
      # token is not installed in the organization.
      - name: Check available runners
        if: "${{ inputs.runner_tag != 'ubuntu-latest' && steps.generate-token.outcome == 'success' }}"
        continue-on-error: true
        id: set-runner
        env:
           AUTH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          runners=$(curl -s -H "Accept: application/vnd.github+json" -H "Authorization: token $AUTH_TOKEN" "$GITHUB_API_URL/orgs/$GITHUB_REPOSITORY_OWNER/actions/runners")
          available=$(echo "$runners" | jq '.runners[] | select(.status == "online" and .labels[].name == "${{ inputs.runner_tag }}")')
          if [ -n "$available" ]; then
            echo "RUNNER=${{ inputs.runner_tag }}" >> $GITHUB_ENV
          else
            echo "RUNNER=ubuntu-latest" >> $GITHUB_ENV
            echo "::error::Self-hosted runner is not available, run on GH runner"
          fi

      # The self-hosted runner is chosen if it is accessible
      # and available.
      # Otherwise, a GH runner is used. 
      - name: Final choose
        id: final
        run: |
          if [[ "${{ inputs.runner_tag }}" == "ubuntu-latest" ]]; then
            echo "runner-tag=ubuntu-latest" >> $GITHUB_OUTPUT
            echo "::notice::The chosen runner is ubuntu-latest"
          elif [[ "${{ steps.set-runner.outcome }}" != "success" ]]; then
            echo "runner-tag=ubuntu-latest" >> $GITHUB_OUTPUT
            echo "::warning::The selected runner is ubuntu-latest -- You requested ${{ inputs.runner_tag }} but it is not available."
          else
            echo "runner-tag=${{ env.RUNNER }}" >> $GITHUB_OUTPUT
            echo "::notice::The chosen runner is ${{ env.RUNNER }}"
          fi

  build-install-test:
    name: 'Build, install and test Arcane Framework'
    needs: check-runner
    runs-on: ${{ needs.check-runner.outputs.runner-tag }}
    container:
      image: ${{inputs.image}}

    steps:

      # actions/cache dosen't accept . or .. in its path.
      - name: Define environment paths
        shell: bash
        run: |
          echo "SOURCE_DIR=${GITHUB_WORKSPACE}/framework" >> $GITHUB_ENV
          echo "BUILD_DIR=${GITHUB_WORKSPACE}/build" >> $GITHUB_ENV
          echo "INSTALL_DIR=${GITHUB_WORKSPACE}/install" >> $GITHUB_ENV
          echo "LOG_DIR=${GITHUB_WORKSPACE}/log" >> $GITHUB_ENV
          echo "CT_RESULT_DIR=${GITHUB_WORKSPACE}/test" >> $GITHUB_ENV
          if [[ "${{ inputs.use_cache }}" == "true" ]]; then
            if [[ "${{ needs.check-runner.outputs.runner-tag }}" == "ubuntu-latest" ]]; then
              echo "CCACHE_DIR=${GITHUB_WORKSPACE}/ccache" >> $GITHUB_ENV
            else
              echo "CCACHE_DIR=${GITHUB_WORKSPACE}/../ccache" >> $GITHUB_ENV
            fi
          else
            echo "CCACHE_DIR=" >> $GITHUB_ENV
          fi

      - name: Create directories
        shell: bash
        run: |
          rm -fr ${{ env.SOURCE_DIR }} \
            ${{ env.BUILD_DIR }} \
            ${{ env.INSTALL_DIR }} \
            ${{ env.LOG_DIR }} \
            ${{ env.CT_RESULT_DIR }}
          mkdir -p ${{ env.SOURCE_DIR }} \
            ${{ env.BUILD_DIR }} \
            ${{ env.INSTALL_DIR }} \
            ${{ env.LOG_DIR }} \
            ${{ env.CT_RESULT_DIR }} 
          if [[ "${{ inputs.use_cache }}" == "true" ]]; then
            mkdir -p ${{ env.CCACHE_DIR }}
          fi

      - name: Upload log artifact
        uses: actions/upload-artifact@v6
        with:
          name: ${{ inputs.artifact_key_prefix }}-log_config_build-artifact
          path: ${{ env.LOG_DIR }}
          retention-days: 7
          include-hidden-files: FALSE
          if-no-files-found: warn
          compression-level: 6
          overwrite: false

      - name: Clear dirs
        if: always()
        shell: bash
        run: |
          rm -fr ${{ env.SOURCE_DIR }} \
            ${{ env.BUILD_DIR }} \
            ${{ env.INSTALL_DIR }} \
            ${{ env.LOG_DIR }} \
            ${{ env.CT_RESULT_DIR }}
