name: 'Build, install and test Arcane Framework'

on:
  workflow_call:
    inputs:
      image:
        description: 'Docker image for the workflow'
        type: string
        required: true

      compilo_name:
        description: 'Compiler name (gcc, clang)'
        type: string
        required: false
        default: 'gcc'
      compilo_version:
        description: 'Compiler version (12, 16, ...)'
        type: string
        required: false
        default: ''
      mpi:
        description: 'MPI (OMPI, MPICH)'
        type: string
        required: false
        default: 'OMPI'
      acc_compilo_name:
        description: 'Accelerator compiler name (cuda, acpp, clang_cuda, rocm)'
        type: string
        required: false
        default: ''
      acc_compilo_version:
        description: 'Accelerator compiler version (125, 126, ...) or empty str'
        type: string
        required: false
        default: ''
      use_mold:
        description: 'Use mold linker ? (true/false/auto)'
        type: string
        required: false
        default: 'auto'
      type_build:
        description: 'Type of build (Debug, Check, Release)'
        type: string
        required: false
        default: 'Release'
      cmake_additionnal_args:
        description: 'Additionnal arguments for configure'
        type: string
        required: false
        default: ''
      verbose:
        description: 'Add verbose args for make/ninja'
        type: boolean
        required: false
        default: false
      ccache_debug_mode:
        description: 'Activate CCache debug mode'
        type: boolean
        required: false
        default: false
      with_samples:
        description: 'Compile samples too ? Require install_dir.'
        type: boolean
        required: false
        default: true
      with_rand_script:
        description: 'Disabling randomly selected packages ?'
        type: boolean
        required: false
        default: false

      execute_tests:
        description: 'Execute tests ?'
        type: boolean
        required: false
        default: true
      cleanup_output_after_test:
        description: 'Remove output dir of each successful test ?'
        type: boolean
        required: false
        default: true
      excluded_tests:
        description: 'Regex with exclude tests'
        type: string
        required: false
        default: ''
      excluded_tests_with_labels:
        description: 'Labels of exclude tests'
        type: string
        required: false
        default: ''
      ctest_output_on_failure:
        description: 'Activate output on failure'
        type: boolean
        required: false
        default: true
      ctest_additionnal_args:
        description: 'Additionnal arguments for testing'
        type: string
        required: false
        default: ''

      use_cache:
        description: 'Use cache ? (true/false)'
        type: string
        required: false
        default: 'true'
      cache_key_prefix:
        description: 'Cache key prefix'
        type: string
        required: false
        default: 'aio'
      artifact_key_prefix:
        description: 'Artifact key prefix'
        type: string
        required: false
        default: 'artifact'

      runner_tag:
        description: 'Runner tag'
        type: string
        required: false
        default: 'ubuntu-latest'
        # options:
        # - 'ubuntu-latest'
        # - 'm-1'


env:
  # OpenMPI
  OMPI_ALLOW_RUN_AS_ROOT: 1
  OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
  # To tell OpenMPI we may use more processus than available cores
  OMPI_MCA_rmaps_base_oversubscribe : true
  ASAN_OPTIONS: 'detect_leaks=false'
  

jobs:

  build-install-test:
    name: 'Build, install and test Arcane Framework'
    runs-on: m-1
    container:
      image: ${{inputs.image}}

    steps:
      - name: Create directories
        shell: bash
        run: |
          touch aaa.log

      - name: Upload log artifact
        uses: actions/upload-artifact@v4.3.6
        with:
          name: test
          path: aaa.log

      - name: Clear dirs
        if: always()
        shell: bash
        run: |
          rm aaa.log
